[package]
name = "nomia-core"
version = "2.0.2"
authors = ["Shea Levy <shea.levy@scarf.sh>"]
edition = "2018"

[features]
alloc = []

[dependencies]
libc = "0.2"

[build-dependencies]
anyhow = "1.0"
cc = "1.0"
bindgen = "0.58"
